---

apiVersion: {{ service_api_version }}
kind: Service
metadata:
  name: {{ app_name }}
  namespace : {{ namespace }}
  labels:
    app: {{ app_name }}
    service: {{ app_name }}
spec:
  selector:
    app: {{ app_name }}
    service: {{ app_name }}
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
